# Generated by Django 3.1.4 on 2020-12-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20201210_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(default='', upload_to='upload_data'),
        ),
        migrations.AlterField(
            model_name='person',
            name='registerno',
            field=models.IntegerField(null=True),
        ),
    ]
