# Generated by Django 3.1.4 on 2020-12-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20201211_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(default='', upload_to='webapp/static/images/'),
        ),
    ]
