# Generated by Django 3.1.4 on 2020-12-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20201211_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='g_father',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='pin',
            field=models.CharField(default='', max_length=50),
        ),
    ]
