# Generated by Django 3.1.4 on 2020-12-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20201215_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='qualification',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='person',
            name='g_father',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='person',
            name='pin',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='person',
            name='sername',
            field=models.CharField(default='', max_length=15),
        ),
    ]
