# Generated by Django 3.1.4 on 2020-12-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20201221_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='father_registerno',
            field=models.IntegerField(null=True),
        ),
    ]
