# Generated by Django 3.1.4 on 2020-12-22 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_person_father_registerno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='pin',
        ),
    ]
