# Generated by Django 3.1.4 on 2020-12-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_remove_person_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='father_registerno',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='registerno',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
